import * as React from 'react';
import { Text, View, StyleSheet } from 'react-native';
import Constants from 'expo-constants';

export default function AboutUsScreen() {
  return (
   
   <View style={{padding:17,flex:1,marginTop:0}}>
  
  <View style={{marginBottom:10}}>
  <Text style={{fontWeight:"bold",color:"black",fontSize:25}}>Brain<Text style={{fontWeight:"bold",color:"blue",fontSize:25}}>Care</Text></Text>
  </View>

  <View>

  <Text style={{textAlign:'justify',fontSize:15,color:"grey",lineHeight:25}}>BrainCare is an Application that provides a novel method that
uses Brain MRI images to detect the presence of brain tumor followed by recommendations
of the hospital for treatment. Our application takes brain MRI images of patients as input
and detects the presence of tumor. By detecting the presence of a brain tumor in its early
stages, the user can receive timely medical intervention and improve their chances of survival.
Furthermore, it considers all useful data from various hospitals is taken into consideration
then useful and appropriate information about brain tumor is recommended to the user as
well as hospital which are specialized to treat the tumor is recommended based on various
attributes such as location, medical specialties, quality of care, and patient satisfaction ratings. The application is also useful for recommending specialized hospitals for the treatment
of brain tumors, as different hospitals have varying levels of expertise in treating different
types of tumors. Along with the recommendation, the confidence of the detection is also
displayed to the user so that the user gets the assurance of results generated by the system.
As a result the user can receive essential medical advice and treatment as soon as possible.
</Text>

<Text style={{textAlign:'justify',fontSize:14,color:"black"}}>
©Copyright 2023 BrainCare
</Text>

  </View>


  
   


   </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#ecf0f1',
    padding: 8,
  },
  paragraph: {
    margin: 24,
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
  },
});
